apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring-system
spec:
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-adapter
    version: 1.4.0
